### ISSUE TITLE
Allow non-interactive rebase

### ISSUE THREAD

**Issue by jazzdragon** [uptech/git-ps-rs#138] opened 2022-07-18 07:57 UTC
It would be nice to allow doing something like `gps rebase --edit 2` where 2 is the patch index.

Motivation: most often I know exactly what I want out of the rebase, and going through the interactive interface is time consuming.

**Comment by drewdeponte** [comment] 2023-10-13 17:54
This is a duplicate of #191 so closing it.

**Closed by drewdeponte** 2023-10-13 17:54 UTC
