### ISSUE TITLE
`gps ls` reports: `rr+!` after `gps sync`; following `gps rr` and `gps rebase`

### ISSUE THREAD

**Issue by ctsstc** [uptech/git-ps-rs#122] opened 2022-06-30 23:30 UTC
My patch status after rebasing and running a sync shows that the remote patch has changed, even though I just ran sync.

## Flow

1. `gps rr 0`
2. `gps rebase` (`gps ls` shows `rr+` afterwards like it should)
3. `gps sync 0` 
4. `gps ls` (shows `rr+!`)

> Note: Used index `0` as an example to denote the same patch.

**Comment by drewdeponte** [comment] 2022-07-01 02:59
I was able to reproduce the issue with the following.

## Initial State

```
✔ git la
* ef9101c - G - (HEAD -> main) Add foo() function (39 seconds ago) <Drew De Ponte>
* a34b62b - G - (origin/main) Initial skeleton (9 months ago) <Drew De Ponte>
```

```
✔ gps ls
0           ef9101 Add foo() function
```

## Request Review

```
✔ gps rr 0
Switched to branch 'ps/tmp/isolate'

  The isolate_post_checkout hook was not found!

  This hook is NOT required but it is strongly recommended that you set it
  up. It is executed after the temporary isolation branch has been created,
  the patch cherry-picked into it and the isolation branch checked out.

  It is intended to be used to further verify patch isolation by verifying
  that your code bases build succeeds and your test suite passes.

  You can effectively have it do whatever you want as it is just a hook.
  An exit status of 0, success, informs gps that the further isolation
  verification was successful. Any non-zero exit status will indicate failure
  and cause gps to abort.

  You can find more information and examples of this hook and others at
  the following.

  https://github.com/uptech/git-ps-rs#hooks

Switched to branch 'main'
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 797 bytes | 797.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote:
remote: Create a pull request for 'ps/rr/add_foo___function' on GitHub by visiting:
remote:      https://github.com/uptech/git-ps-test/pull/new/ps/rr/add_foo___function
remote:
To github.com:uptech/git-ps-test.git
 * [new branch]      ps/rr/add_foo___function -> ps/rr/add_foo___function

Creating pull request for ps/rr/add_foo___function into main in uptech/git-ps-test

https://github.com/uptech/git-ps-test/pull/32


A new release of gh is available: 2.12.1 → 2.13.0
To upgrade, run: brew update && brew upgrade gh
https://github.com/cli/cli/releases/tag/v2.13.0
```

```
✔ git la
* d84d74b - G - (origin/ps/rr/add_foo___function, ps/rr/add_foo___function) Add foo() function (3 minutes ago) <Drew De Ponte>
| * 7bcd919 - G - (HEAD -> main) Add foo() function (3 minutes ago) <Drew De Ponte>
|/
* a34b62b - G - (origin/main) Initial skeleton (9 months ago) <Drew De Ponte>
```

```
✔ gps ls
0    rr     7bcd91 Add foo() function
```

## Amend

```
✔ gps a
[main f6f1d89] Add foo() & bar() functions
 Date: Thu Jun 30 22:20:02 2022 -0400
 1 file changed, 8 insertions(+)
```

```
✔ git la
* f6f1d89 - G - (HEAD -> main) Add foo() & bar() functions (14 minutes ago) <Drew De Ponte>
| * d84d74b - G - (origin/ps/rr/add_foo___function, ps/rr/add_foo___function) Add foo() function (14 minutes ago) <Drew De Ponte>
|/
* a34b62b - G - (origin/main) Initial skeleton (9 months ago) <Drew De Ponte>
```

```
✔ gps ls
0    rr+    f6f1d8 Add foo() & bar() functions
```

## Sync

```
✔ gps sync 0
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 817 bytes | 817.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:uptech/git-ps-test.git
 + d84d74b...21be078 ps/rr/add_foo___function -> ps/rr/add_foo___function (forced update)
```

```
✔ git la
* 21be078 - G - (origin/ps/rr/add_foo___function, ps/rr/add_foo___function) Add foo() & bar() functions (19 minutes ago) <Drew De Ponte>
| * f6f1d89 - G - (HEAD -> main) Add foo() & bar() functions (19 minutes ago) <Drew De Ponte>
|/
* a34b62b - G - (origin/main) Initial skeleton (9 months ago) <Drew De Ponte>
```

```
✔ gps ls
0    rr+!   f6f1d8 Add foo() & bar() functions
```

At this point the state file's content was the following:

```json
{
  "a7d356b4-8a16-4857-a7a1-d46e6556321b": {
    "patch_id": "a7d356b4-8a16-4857-a7a1-d46e6556321b",
    "state": {
      "RequestedReview": [
        "origin",
        "ps/rr/add_foo___function",
        "c4c9e4e17e18d6bf6c966bf033d535a39e8bdce8",
        "c4c9e4e17e18d6bf6c966bf033d535a39e8bdce8"
      ]
    }
  }
}
```

The raw commits for this patch on local stack and on the remote are as follows respectively.

```
✔ git show --pretty=raw f6f1d89
commit f6f1d89d375bdf9a0902942d623e4ad5cab4bc24
tree 82732c99988e7c7083942e6f2d0721670cabac54
parent a34b62b61d1675073eb1df953f1cdfc01232cceb
author Drew De Ponte <cyphactor@gmail.com> 1656642002 -0400
committer Drew De Ponte <cyphactor@gmail.com> 1656642827 -0400
gpgsig -----BEGIN PGP SIGNATURE-----

 iQEzBAABCAAdFiEEZ4qmf6cBz6fWZrzoQcXSxuWvlEwFAmK+XRoACgkQQcXSxuWv
 lExDOAf7ByARZ0D3R84ww49saitgqjRvpq62E1xMqlGVux7BuUG4cafF1yXFLZOp
 wYNWIRxqlRVsqJyXZQHDF8nkDw49tUAiAVPLJGEbUBLM6CS8Rh0KccvC37DpnJ/V
 YsrUVtLHNJFjQaKncg8qt7buKHget5B3EL/igONIDzAXPRhXbZBZnOPpNmZP7LYY
 OTvfBU6ywdYChCIX40VZBle5ar5345GrKjmjax95j7Rywe8MJ04v0IeGlcI/1aiK
 ARvDS+eOVMcI3bFYAtoBXnOHxJFuPOB4/fFRdwz13HihwZGGu1zrKWts3WT2Mu/u
 BiSpg1cDmR7NNyYt5IG9xbBsLL8VNw==
 =YU3s
 -----END PGP SIGNATURE-----

    Add foo() & bar() functions

    ps-id: a7d356b4-8a16-4857-a7a1-d46e6556321b

diff --git a/src/main.rs b/src/main.rs
index e7a11a9..bffb179 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,3 +1,11 @@
 fn main() {
     println!("Hello, world!");
 }
+
+fn foo() {
+  println!("foo");
+}
+
+fn bar() {
+  println!("bar");
+}
```

```
✔ git show --pretty=raw 21be078
commit 21be078f7373fda523659926e2ce137c6599f603
tree 82732c99988e7c7083942e6f2d0721670cabac54
parent a34b62b61d1675073eb1df953f1cdfc01232cceb
author Drew De Ponte <cyphactor@gmail.com> 1656642002 -0400
committer Drew De Ponte <cyphactor@gmail.com> 1656643096 -0400
gpgsig -----BEGIN PGP SIGNATURE-----

 iQEzBAABCAAdFiEEZ4qmf6cBz6fWZrzoQcXSxuWvlEwFAmK+XhcACgkQQcXSxuWv
 lEyGDQf/fx+vYVvQKSEnVwPfJgL3K0CHj4YTZDdKHDE1DxyuZZivj5YbM60Rsk8J
 +CF8hi3G3hsfLgVdv0uiYSB6kIMQTVxzrNjb+kDJZ6uu0FlIBLvtKbkYNG6VpZdJ
 eVLRAi8Y8xehzYc2oeRGtI6Gwu5O/Sg50YGqq67yodzPqmceBVu9gE5xQ2rjlqMI
 7EITU69yq/oQ5GsWuWlzW4uqQqMGoEnfkcQtVECgV3FhqoBdyFMxI5oBIUicBoqA
 SSLvrXRV1GlVt+U1dtifaIPU/tEtYvCXoWf5zat0oXMuvFOeg2OI8fxEzqXkwSg9
 7cqRsVJw1w7tBoF5sG3ZgKjbqrz9ng==
 =enA2
 -----END PGP SIGNATURE-----

    Add foo() & bar() functions

    ps-id: a7d356b4-8a16-4857-a7a1-d46e6556321b

diff --git a/src/main.rs b/src/main.rs
index e7a11a9..bffb179 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,3 +1,11 @@
 fn main() {
     println!("Hello, world!");
 }
+
+fn foo() {
+  println!("foo");
+}
+
+fn bar() {
+  println!("bar");
+}
```

**Comment by drewdeponte** [comment] 2022-07-01 03:46
Ok, did some digging and I think I figured out what the problem is. I think the state is not being updated when you sync if the patch is in a RequestReview state. We can see this on the following line.

https://github.com/uptech/git-ps-rs/blob/main/src/ps/public/sync.rs#L56

It just passes whatever the current patch metadata back into the update.

**Comment by drewdeponte** [comment] 2022-07-01 04:31
The fix for this issue has been integrated into mainline so I am closing this issue.

**Closed by drewdeponte** 2022-07-01 04:31 UTC
Labels: bug

**Comment by drewdeponte** [comment] 2022-07-01 04:36
@ctsstc I personally hadn't run into this issue before because I generally use the `gps rr <patch-index>` to conceptually re-request review after I have changed a patch.

I think conceptually re-requesting review for an updated patch is the most straightforward workflow but sync should do the correct thing as well when in this state.

**Comment by drewdeponte** [comment] 2022-07-01 04:57
I just cut release 5.3.1 which includes this fix

**Comment by ctsstc** [comment] 2022-07-01 17:08
I did notice yesterday that running `gps rr` again showed the proper status. I think I reach for sync when I make a quick and trivial change like changing the commit message and I want to skip the `rr` hooks.

Thanks for this fix 🎉

**Comment by drewdeponte** [comment] 2022-07-01 17:23
I don't know what the valid scenario is for skipping the isolation verification. Seems like you probably really wouldn't want to do that.
